"use client";

import { useState } from "react";

export default function Home() {
  const [image, setImage] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setImage(file);
    setPreview(URL.createObjectURL(file));
  };

  return (
    <main className="min-h-screen bg-gray-100 flex flex-col items-center justify-center p-4">
      <div className="w-full max-w-xl bg-white p-6 rounded-2xl shadow-lg text-center">
        <h1 className="text-3xl font-bold mb-2">Is this real… or AI?</h1>
        <p className="text-gray-600 mb-6">
          Upload an image to detect if it was generated by AI.
        </p>

        <input
          type="file"
          accept="image/*"
          onChange={handleImageUpload}
          className="mb-4"
        />

        {preview && (
          <div className="mt-4">
            <img
              src={preview}
              alt="Preview"
              className="rounded-lg max-h-64 mx-auto"
            />
          </div>
        )}

        <button
          disabled={!image}
          className="mt-6 bg-blue-600 text-white py-2 px-6 rounded-xl disabled:opacity-50"
        >
          Check Image
        </button>
      </div>

      <footer className="mt-10 text-sm text-gray-500">
        © AgreeMate
      </footer>
    </main>
  );
}
